import type { CalendarEvent } from "./CalendarEvent";
import type { ListingAccessInstruction } from "./ListingAccessInstruction";
import type { ListingAmenity } from "./ListingAmenity";
import type { ListingPhoto } from "./ListingPhoto";
import type { ListingPolicy } from "./ListingPolicy";
import type { ListingRule } from "./ListingRule";
import type { ListingTermPrice } from "./ListingTermPrice";
import type { ListingType } from "./ListingType";
import type { Organization } from "./Organization";
import type { Rating } from "./Rating";
import type { RentalUnit } from "./RentalUnit";

{/*  ===================================THIS FILE WAS AUTO GENERATED=================================== */}

export type Listing = {
    listingID: string;
    rentalUnitID: string;
    listingTypeID: string;
    organizationID: string;
    title: string;
    description: string;
    checkInDoorCode: string;
    rating: number;
    reviews: number;
    tag: string;
    isFurnished: boolean;
    bedrooms: number;
    bathrooms: number;
    squareFeet: number;
    baseMonthlyRentAmount: number;
    securityDepositAmount: number;
    yearBuilt: number;
    status: string;
    publishedAt: string;
    unpublishedAt: string;
    currency: string;
    availableFrom: string;
    availableTo: string;
    minimumLeaseMonths: number;
    maximumLeaseMonths: number;
    applicationDeadline: string;
    notes: string;
    wIFINetwork: string;
    wIFIPassword: string;
    acceptingApplications: boolean;
    capturedBy: string;
    capturedDate: string;
    updatedDate: string;
    updatedBy: string;
    rentalUnit: RentalUnit;
    listingType: ListingType;
    organization: Organization;
    reviewList: Rating[];
    listingTermPrices: ListingTermPrice[];
    listingAccessInstructions: ListingAccessInstruction[];
    listingPhotos: ListingPhoto[];
    listingAmenities: ListingAmenity[];
    listingRules: ListingRule[];
    listingPolicies: ListingPolicy[];
    calendarEvents: CalendarEvent[];
};
