import type { ApplicationOccupant } from "./ApplicationOccupant";
import type { CalendarEvent } from "./CalendarEvent";
import type { Lease } from "./Lease";
import type { LeaseDocuments } from "./LeaseDocuments";
import type { Listing } from "./Listing";
import type { OrganizationMember } from "./OrganizationMember";
import type { ReservationHold } from "./ReservationHold";
import type { Tenant } from "./Tenant";
import type { TenantEmergencyContact } from "./TenantEmergencyContact";
import type { TenantEmployment } from "./TenantEmployment";
import type { TenantGuarantor } from "./TenantGuarantor";
import type { TenantInvitation } from "./TenantInvitation";
import type { TenantScreeningCheck } from "./TenantScreeningCheck";
import type { ViewingAppointments } from "./ViewingAppointments";

{/*  ===================================THIS FILE WAS AUTO GENERATED=================================== */}

export type RentalApplication = {
    rentalApplicationID: string;
    applicationCode: string;
    listingID: string;
    tenantID: string;
    desiredMoveInDate: string;
    desiredMoveOutDate: string;
    requestedLeaseTermMonths: number;
    adultOccupantCount: number;
    childOccupantCount: number;
    petCount: number;
    proposedMonthlyRentAmount: number;
    currency: string;
    status: string;
    screeningStatus: string;
    leaseContractReviewed?: boolean;
    verificationAuthorization?: boolean;
    notes: string;
    submittedAt: string;
    reviewedAt: string;
    reviewedByOrganizationMemberID: string;
    approvedAt: string;
    declinedAt: string;
    declineReason: string;
    expiresAt: string;
    capturedDate: string;
    capturedBy: string;
    updatedDate: string;
    updatedBy: string;
    listing: Listing;
    tenant: Tenant;
    reviewedByOrganizationMember: OrganizationMember;
    applicationOccupants?: ApplicationOccupant[];
    leaseDocuments?: LeaseDocuments[];
    tenantGuarantors?: TenantGuarantor[];
    tenantEmergencyContacts?: TenantEmergencyContact[];
    tenantEmployments?: TenantEmployment[];
    tenantScreeningChecks?: TenantScreeningCheck[];
    tenantInvitations?: TenantInvitation[];
    reservationHolds?: ReservationHold[];
    viewingAppointments?: ViewingAppointments[];
    calendarEvents?: CalendarEvent[];
    leases?: Lease[];
};
